// LES CITATIONS DU PUPITRE — le prêche dépend de l'HUMEUR du prêtre.
// Prêtre content (pièce donnée, ou jamais dérangé) → l'évangile selon Céline.
// Prêtre vénère (pièce refusée) → textes à venir (Vincent) ; en attendant,
// fallback automatique sur les sermons absurdes de sermons.js.
//
// Vincent : colle ici autant de citations que tu veux (evene, etc.) —
// une chaîne par citation, virgule à la fin. \n = saut de ligne dans le prêche.
// `auteur` s'affiche en signature sous la citation (mets null pour aucune).
// It42 : les 100 citations de Vincent intégrées ; les suites naturelles sont
// regroupées en un seul prêche (versets multi-lignes, ton liturgique).

export const CITATIONS = {
  joyeux: {
    auteur: 'Céline Dion',
    textes: [
      "Je ne suis pas une superstar. Je suis Céline.",
      "La musique, c'est thérapeutique,\nune façon extraordinaire de s'exprimer.",
      "Il y a tellement de façons différentes de dire « je t'aime »\net de parler d'amour dans les chansons.",
      "La famille, c'est une richesse incroyable :\nça donne des outils pour affronter les moments extraordinaires,\nles moments plus difficiles, les hauts, les bas.",
      "Le bonheur ne se cache pas.",
      "Mon retour sur scène, ça va se passer.\nC'est pour ça que je travaille super fort.\nÇa va se passer.",
      "Ma voix était le chef d'orchestre de ma vie.\nJe la suivais.",
      "Quand ta voix t'apporte de la joie,\ntu es le meilleur de toi-même.",
      "Ce n'est pas dur de faire un show ;\nc'est dur d'annuler un show.",
      "Je savais qu'ils voulaient Céline Dion.",
      "Une performance est beaucoup plus grande\nqu'une chanson.",
      "J'avais besoin de médicaments pour fonctionner.\nLe spectacle devait continuer.",
      "Si je ne peux pas courir, je marcherai.\nSi je ne peux pas marcher, je ramperai.\nMais je n'arrêterai pas.",
      "Je vais remonter sur scène,\nmême si je dois ramper.",
      "Ma voix sera entendue,\nparce que je le veux.",
      "Je chante parce que ça fait partie de ma vie.",
      "Aimer chanter et performer,\nc'est ce que je fais et ce que j'aime.",
      "Je n'enregistre que les chansons qui me touchent.",
      "Je ne chante pas gratuitement.\nC'est mon travail.",
      "Tu es payé pour ce que tu fais.\nEt je travaille dur.",
      "Toute ma vie, il n'y a eu que discipline,\ndiscipline, discipline.",
      "Je ne suis en compétition avec personne\nsauf moi-même.",
      "Mon but est de battre ma dernière performance.",
      "Pour moi, chanter, c'était la vraie vie.",
      "Je ne mets pas ma carrière en danger\nquand j'essaie quelque chose en musique.",
      "Je peux essayer ce que je veux musicalement.",
      "Je n'écoute pas ma propre musique à la maison.",
      "Je ne suis pas une fan de musique,\nbizarrement.",
      "Chaque chanson parle d'amour\nd'une manière différente.",
      "J'ai partagé toute ma vie,\nprivée et publique.",
      "Les gens me manquent.",
      "Même si j'ai parcouru le monde,\nje n'ai presque rien vu.\nParfois, on appelle ça le prix à payer.",
      "Je suis la plus jeune de 14 enfants.",
      "Comme je parlais rarement,\nquand j'ai l'occasion de parler, je parle.",
      "J'ai commencé à cinq ans, sur la table de cuisine,\navec ma famille derrière moi.",
      "Je sais d'où je viens.\nJe sais exactement où je vais.",
      "Mes enfants me donnent l'équilibre\npour bien vivre.",
      "Ma réussite, c'est ma famille.",
      "Je veux réussir encore plus comme mère\nque dans le show-business.",
      "Être mère est la chose la plus difficile\nque j'aurai à faire.",
      "Quand tu es entouré d'enfants,\nl'enfant en toi revient.",
      "J'ai donné la vie, et c'est magnifique.",
      "Mon enfant n'a pas seulement été porté par moi,\nmais par l'univers.",
      "Il n'y a pas de plus grand amour\nque celui d'une mère pour son enfant.",
      "La famille, l'amour et les enfants,\nc'est tout pour moi.",
      "La première chanson que j'ai enregistrée\na été écrite par ma mère.",
      "Je suis Québécoise-canadienne.",
      "Mes racines sont ce qu'il y a\nde plus important pour moi.",
      "Je n'ai jamais été cool —\net je m'en fiche.",
      "Vieillir, ce n'est pas vieillir :\nc'est mûrir et apprendre.",
      "Je n'étais pas jolie, j'avais des problèmes de dents,\nj'étais très mince.\nJe ne rentrais pas dans le moule.",
      "Je n'étais pas bonne à l'école.",
      "Ne fais pas de ta carrière ta vie.\nFais de ta carrière ta passion, pas ton identité.\nTu vaux beaucoup plus que ta carrière.",
      "Le plus dur dans la vie,\nc'est de trouver l'équilibre.",
      "Plus tu as du succès,\nplus tu regardes de l'autre côté de la barrière.",
      "Regarde à l'intérieur de toi-même.",
      "Ce que je décide de faire doit avoir du sens.\nSinon, je ne le fais pas.",
      "Mes pieds sont plus ancrés qu'avant.",
      "Je ne m'accroche pas à un rêve,\nje m'accroche à ma vie.",
      "Je ne retournerais jamais à mes vingt ans.\nLe meilleur reste à venir.",
      "Je ne vais pas devenir Rihanna.\nPersonne ne peut être Rihanna, sauf Rihanna.",
      "Je suis très à l'aise dans ma peau.",
      "Je pense que ça dérange les gens\nde voir quelqu'un heureux et qui réussit.\nAlors ils essaient de trouver ce qui ne va pas chez lui.",
      "Quand une fille aime ses chaussures,\nelle les fait toujours aller.",
      "Je marche la chaussure,\nla chaussure ne me marche pas.",
      "Certaines personnes prennent de la drogue ;\nmoi, j'achète des chaussures.",
      "J'ai environ 3 000 paires de chaussures.",
      "J'achète souvent des cadeaux pour moi-même.",
      "Parfois, je peux dépenser 100 000 dollars\nen une journée dans une boutique chic.",
      "Je peux faire entrer mon pied\ndans n'importe quelle chaussure que j'aime.",
      "Dans ma salle de bain,\nil y a un peu de tout.",
      "J'adore les jupes crayon,\nmais je cherche toujours le haut qui va avec.",
      "Avec une robe, je sais que le haut va avec le bas.\nComme ça, je ne peux pas me tromper.",
      "J'ai hâte de faire des choses normales.\nJ'ai hâte d'aller acheter mes propres tomates.\nJ'ai hâte de me lever le matin et d'avoir mauvaise mine.\nJ'ai hâte de m'ennuyer.",
      "Revenir travailler à Vegas,\nc'est comme partir en vacances pour moi.",
      "Le seul échec,\nc'est de ne pas savoir être heureux.",
      "C'est au moment où tu crois que tu ne peux pas\nque tu peux.",
      "L'amour ne demande pas pourquoi.",
      "L'amour parle avec le cœur.",
      "L'amour ne réfléchit pas deux fois.",
      "L'amour arrive d'un coup,\nou murmure de loin.",
      "L'amour vient à ceux qui y croient.",
      "Il n'y a pas de chemin facile\nquand tu veux vraiment quelque chose.",
      "Ne renonce pas à ta foi.",
      "Garde les tiens près de toi.",
      "Si tu veux aller vite, va seul.\nSi tu veux aller loin, va ensemble.",
      "Nous avons grandi ensemble.\nNous sommes devenus une famille.\nJe suis devenue ce que je suis grâce à toutes ces personnes.",
      "Je suis une personne normale,\nmême si j'ai une vie extraordinaire.",
      "Mes fans ont acheté cette maison.\nIls ont acheté mes disques.\nIls viennent aux concerts, même quand c'est cher.",
      "Je travaille dur,\nmais j'ai aussi eu beaucoup de chance.",
      "On a peut-être créé notre propre magie.",
    ],
  },
  vener: {
    auteur: null,
    textes: [], // vide = les sermons de comptoir de sermons.js prennent le relais
  },
};
